services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: car_ads_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/car_ads_db
      SECRET_KEY: your_super_secret_and_long_key_here_replace_this_in_production
    depends_on:
      - db
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata: